# Generated by Django 5.1.3 on 2025-02-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='about',
            new_name='content',
        ),
    ]
