# Generated by Django 5.1.3 on 2025-02-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.catagory'),
            preserve_default=False,
        ),
    ]
