# Generated by Django 5.1.3 on 2025-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.URLField(),
        ),
    ]
