# Generated by Django 5.1.3 on 2025-02-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='blog/aboutus'),
        ),
    ]
